apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: weavescope-ingress
  namespace: weave
  annotations:
    nginx.ingress.kubernetes.io/add-base-url: "true"
    nginx.ingress.kubernetes.io/proxy-body-size: "0"
    nginx.ingress.kubernetes.io/ssl-passthrough: "true"
spec:
  rules:
  - host: weavescope.example.com
    http:
      paths:
        - path: /
          backend:
            serviceName: weave-scope-app
            servicePort: 80
